@startuml
'https://plantuml.com/use-case-diagram

rectangle EHR {
    'decide direction of diagram
    left to right direction
    'add actors
    :Patient:
    :Secretary:
    :Personal-Doctor:
    :Hospital-Personnel:
    rectangle use-cases {
        'add use cases
        usecase "sign in" as sign_in
        usecase "appointment booking" as appointment_booking
        rectangle Journal {
            usecase UC2 as "HP: fill journal
            --
            - Prescriptions
            __
            - History
            (appointments + notes)
            __
            - Test
            (results, notes, images)
            __
            - Scan
            (results, notes, images)
            "

            usecase UC3 as "PD: fill journal
            --
            - Prescriptions
            __
            - History
            (appointments + notes)
            __
            - Test
            (results, notes, images)
            "
        }
    }

    'relationships;Actors
    Patient --> sign_in : "authentication, view, request date and time"
    Secretary --> appointment_booking : "confirm date, time and location"
    :Hospital-Personnel: --> UC2 : "add"
    :Personal-Doctor: --> UC3 : "edit"

    'relationships;Use-cases
    sign_in .> Journal : extend
    sign_in .> appointment_booking : extend
    appointment_booking .> Journal : extend
}
@enduml


