@startuml
'https://plantuml.com/use-case-diagram

rectangle EHR {
'decide direction of diagram
left to right direction
'add actors
:Patient:
:Secretary:
:Personal-Doctor:
:Hospital-Doctor:
:Nurse:
:Radiographer:
:MRI-personnel:
'Patient right of Secretary
rectangle use-cases {
    'add use cases
    usecase UC1 as "appointment booking"
    usecase UC2 as "fill journal
--
- Prescriptions
__
- History
(notes)
__
- Test
(results, notes, images)
__
- Scan
(results, notes, images)
"
}

'relationships
Patient --> UC1 : "suggest"
Patient --> UC2 : "view"
Secretary --> UC1 : "confirm"
:Personal-Doctor: --> UC2 : "edit"
:Hospital-Doctor: --> UC2 : "add"
Nurse --> UC2 : "add"
Radiographer --> UC2 : "add"
:MRI-personnel: --> UC2 : "add"
}
@enduml


