@startuml

title Renew prescription - sequence diagram

actor Patient as patient

participant sundhed.dk as sundhed

participant MitId as mitid

participant GP_system as gpsystem

actor Doctor as doctor


autonumber

patient -> sundhed : Login
activate patient
activate sundhed

sundhed -> mitid : Prompt login for user
activate mitid

mitid --> patient : Login with MitID


patient -> mitid : 2 factor authentication

mitid --> patient : Login approved

mitid --> sundhed : Authentication\nresponse
deactivate mitid

sundhed -> sundhed : redirect

sundhed --> patient : Display medicinkortet

patient -> sundhed : Request\nprescription renewal

sundhed -> gpsystem : Send prescription\nrenewal nrequest
activate gpsystem

gpsystem -> doctor : Notify doctor\nabout request
activate doctor



alt prescription renewed
    doctor -> gpsystem : prescription renewed

    gpsystem --> sundhed : send new information\nto sundhed

    sundhed --> patient : Notify user


else consultation required
    doctor -> gpsystem : request denied
    deactivate doctor

    gpsystem --> sundhed : send rejection\nto sundhed
    deactivate gpsystem

    sundhed --> patient : Notify user of rejection
    deactivate sundhed
    deactivate patient

end


@enduml
